# _config.yml

title: My Awesome Site
description: A description of my awesome website
baseurl: ""  # The base URL for your site (leave blank if it's a root-level site)
url: "https://yourusername.github.io"  # Your GitHub Pages URL

# Specify the theme here (e.g., `minima`, `jekyll-theme-cayman`, etc.)
theme: jekyll-theme-minima

# Additional configurations (optional)
markdown: kramdown
theme_config:
  sidebar:
    - title: "About"
      url: "/about"
    - title: "Blog"
      url: "/blog"
